# Generated by Django 2.1.7 on 2019-04-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='Brand',
            field=models.CharField(default='null', max_length=120),
        ),
        migrations.AddField(
            model_name='product_details',
            name='Title',
            field=models.CharField(default='null', max_length=120),
        ),
    ]
