# Generated by Django 2.1.7 on 2019-04-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_product_details_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='user',
        ),
    ]
