# Generated by Django 2.1.7 on 2019-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_product_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
