# Generated by Django 2.1.7 on 2019-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20190420_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
