# Generated by Django 2.1.7 on 2019-04-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20190421_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='photo',
            new_name='Picture',
        ),
    ]
