# Generated by Django 2.1.7 on 2019-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='Brand',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='Title',
            field=models.CharField(max_length=120),
        ),
    ]
