# Generated by Django 2.1.7 on 2019-04-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_no',
            field=models.PositiveIntegerField(default='7033574516'),
        ),
    ]
